name: bookworm
description: bookworm application

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  eva_icons_flutter: ^2.0.0
  auto_animated: ^2.1.0
  marquee: ^1.5.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  http: ^0.12.2
  cached_network_image: ^2.2.0+1
  flutter_local_notifications: 1.4.4+5
  shared_preferences: ^0.5.12
  url_launcher: ^5.7.2
  stacked_themes:
  data_connection_checker: ^0.3.4
  step_progress_indicator: ^0.2.4+7
  notification_permissions: ^0.4.8
  app_settings: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0
  hive_listener: ^0.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700